name: Cool Art
favicon: null
layout_spectrum: 0.8632206504698843
typography_spectrum: 0.06351998378522694
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2701434725895524
  lightness: 0.6705566726159304
  saturation: 0.045486096292734146
  rhythmicContrast: 0.03007361339405179
purpose: []
